### ISSUE TITLE
Duplicate setup.md

### ISSUE THREAD

**Issue by mbrukman** [full-stack-deep-learning/fsdl-text-recognizer-2021-labs#2]
https://github.com/full-stack-deep-learning/fsdl-text-recognizer-2021-labs/blob/main/setup.md seems to be a duplicate of https://github.com/full-stack-deep-learning/fsdl-text-recognizer-2021-labs/blob/main/setup/readme.md .

The images all seem to be in the `setup` directory, so the `setup/readme.md` file seems to be the more correct/complete one, as the `setup.md` file is incomplete due to missing image file references.

**Comment by sergeyk** [comment]
That's right, thanks for the suggestion!
