### ISSUE TITLE
Lab 3: Can't achieve 90% accuracy

### ISSUE THREAD

**Issue by oOXpycTOo** [full-stack-deep-learning/fsdl-text-recognizer-2021-labs#31]
Hi, thanks for the course. I faced a problem, that I can't achieve 90% accuracy on EMNISTLines dataset, no matter what I try to do. I even tried to simply execute the initial architecture without any changes, but I get no more than 82% of accuracy. For other experiments in this lab, the accuracy is even worse than it's written in the corresponding readme. Could you please, point out, what I'm doing wrong?
I simply clone the repo and executed this line:
```python training/run_experiment.py --max_epochs=10 --gpus=1 --num_workers=4 --data_class=EMNISTLines --min_overlap=0 --max_overlap=0 --model_class=LineCNNSimple --window_width=28 --window_stride=28```

**Comment by deepseek-eoghan** [comment]
Did you ever try increasing the max_epochs?

**Comment by oOXpycTOo** [comment]
I found the solution and it was just to change the dimension in softmax function for accuracy prediction, as described here: https://github.com/full-stack-deep-learning/fsdl-text-recognizer-2021-labs/issues/27#issue-869823325
