### ISSUE TITLE
PythonPath for Windows - Module Not Found Error

### ISSUE THREAD

**Issue by karthikraja95** [full-stack-deep-learning/fsdl-text-recognizer-2021-labs#4]
I am using a Windows system with a couple of GPUs, I know the repo asks us to use Linux. Just wondering how do I resolve this ModuleNotFoundError: No module named 'text_recognizer' in Windows

I edited the  Environment Variables and added the Path (C:\Users\path\to\fsdl-text-recognizer-2021-labs\) in both User Variables and System variables still gives the same error. Do you have any idea how to approach this?

**Comment by sergeyk** [comment]
You've set `PYTHONPATH`, right?
 https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows-so-it-finds-my-modules-packages

**Comment by karthikraja95** [comment]
Yes, I have set the PYTHONPATH in the environment variable. In my case its something like

C:\Users\*****\AppData\Local\Programs\Python\Python37

**Comment by sergeyk** [comment]
`PYTHONPATH` should be set to the directory in which you want python to find the `text_recognizer` package. This directory can be `.` (current directory), such that if you are in `fsdl-text-recognizer-labs-2021/lab3`, you can run `python -m text_recognizer` and it will find it

**Comment by karthikraja95** [comment]
Thanks for helping me out. I am closing this issue.
