### ISSUE TITLE
make pip-tools fails in Windows

### ISSUE THREAD

**Issue by karthikraja95** [full-stack-deep-learning/fsdl-text-recognizer-2021-labs#5]
I use Windows 10 with a couple of GPUs and conda. I wanted to run lab 1 on my local computer instead of colab. So I installed make using choclately 

Command: `choco install make `

And I ran `make conda-update`, it worked and installed all the dependencies.
Activated the conda environment using` conda activate fsdl-text-recognizer-2021`
Then I ran` make pip-tools`

It throws the following error:

pip._internal.exceptions.DistributionNotFound: No matching distribution found for torchvision==0.8.2 (from -r requirements/prod.in (line 11))
make: *** [Makefile:13: pip-tools] Error 1

I am not sure how to resolve this? If you could help me with these that would be awesome

Traceback just in case:
![Error](https://user-images.githubusercontent.com/40802179/106811570-87f54080-663c-11eb-9553-0c1f358656eb.PNG)

**Comment by sergeyk** [comment]
I don't have Windows so won't be able to test solution or support it. But the error here is that the `torchvision` package doesn't seem to exist for the windows environment.

Maybe relevant: https://stackoverflow.com/questions/50812838/error-in-pip-install-torchvision-on-windows-10
